name: ✨ Feature Request
description: Suggest a new feature or enhancement for GlookoDataWebApp
title: "[Feature]: "
labels: ["✨ Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Why is this needed?
      description: What problem does this solve?
      placeholder: Explain the use case...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or other information
      placeholder: Add any other context or screenshots...
