name: ✨ Feature Request
description: Suggest a new feature or enhancement for GlookoDataWebApp
title: "[Feature]: "
labels: ["✨ Feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        
        **⚠️ Important for Developers and AI Tools:**
        Before beginning work on this feature, please consult [`.github/copilot-instructions.md`](../copilot-instructions.md) for:
        - 🌐 **Code Language Standards** (English-only requirement for all code)
        - 🔄 **Localization Workflow** (mandatory i18next usage for user-facing text)

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any mockups, examples, or other information
      placeholder: Add any other context or screenshots...
