name: 🌟 Pro User Interest
description: Express your interest in becoming a Pro User
title: "[Pro User Interest]: "
labels: ["Pro User Interest"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in becoming a Pro User! Pro Users get managed API keys for AI analysis features, eliminating the need to set up your own API keys.
        
        Please fill out the information below so we can notify you when Pro Users features become available.

  - type: textarea
    id: reason
    attributes:
      label: Why do you want to become a Pro User?
      description: Please tell us in one sentence why you're interested in Pro Users features
      placeholder: I want to use AI analysis features without managing my own API keys...
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Microsoft Account Email
      description: Please provide the email address associated with your Microsoft account. This will be used to grant you Pro User access.
      placeholder: user@example.com
    validations:
      required: true

  - type: dropdown
    id: payment-willingness
    attributes:
      label: Would you be willing to pay approximately $2/month for Pro User access?
      description: This helps cover the API costs for providing managed keys
      options:
        - "Yes, I would pay $2/month"
        - "Maybe, depending on features"
        - "No, I prefer the free tier only"
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other comments or questions about Pro Users features?
      placeholder: Optional additional information...
